BOARD_TAG = lardu_328p
ARDMK_VENDOR = LGT
AVRDUDE_CONF = /etc/avrdude.conf
USER_LIB_PATH = /home/torsten/Arduino/libraries
ARDUINO_LIBS = LiquidCrystal OneWire
ARDUINO_PORT = /dev/ttyUSB0
CXXFLAGS_STD=-std=c++11

include /usr/local/share/arduino/Arduino.mk
