BOARD_TAG    = pro5v328
USER_LIB_PATH = /home/torsten/Arduino/libraries/
ARDUINO_LIBS = OneWire LiquidCrystal
ARDUINO_PORT = /dev/ttyUSB0
CXXFLAGS_STD=-std=c++11

include /usr/share/arduino/Arduino.mk
